apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  serviceMeshControlNodeSelector:
    servicemesh: enabled
  serviceMeshIngressNodeSelector:
    taco-ingress-gateway: enabled
  serviceMeshEgressNodeSelector:
    taco-egress-gateway: enabled
  ingressGatewayLabel:
    gateway: taco-ingress
  egressGatewayLabel:
    gateway: taco-egress
  clusterName: cluster.local
  storageClassName: taco-storage
  istioRevision: "1-10-2"
  istioImageTag: "1.10.2"

charts:
- name: istio-operator
  override:
    revision: $(istioRevision)
    hub: docker.io/istio
    tag: $(istioImageTag)
    operator.resources.limits.cpu: 200m
    operator.resources.limits.memory: 256Mi
    operator.resources.requests.cpu: 50m
    operator.resources.requests.memory: 128Mi

- name: servicemesh-controlplane
  override:
    IstioOperator.revision: $(istioRevision)
    IstioOperator.image.hub: docker.io/istio
    IstioOperator.image.tag: $(istioImageTag)
    IstioOperator.meshConfig.enableTracing: true
    IstioOperator.meshConfig.tracingSampling: 100
    IstioOperator.meshConfig.extensionProviders.envoyExtAuthzGrpc.service: jaeger-operator-jaeger-collector.istio-system.svc
    IstioOperator.meshConfig.extensionProviders.envoyExtAuthzGrpc.port: 14250
    IstioOperator.meshConfig.defaultConfig.discoveryAddress: istiod-$(istioRevision).istio-system.svc:15012
    IstioOperator.meshConfig.defaultConfig.tracing.zipkin.address: jaeger-operator-jaeger-collector.istio-system.svc:9411
    IstioOperator.meshConfig.defaultConfig.tracing.sampling: 100
    IstioOperator.values.global.istioNamespace: istio-system
    IstioOperator.components.pilot.k8s.resources.requests.cpu: 500m
    IstioOperator.components.pilot.k8s.resources.requests.memory: 1024Mi
    IstioOperator.components.pilot.k8s.hpaSpec.minReplicas: 1
    IstioOperator.components.pilot.k8s.nodeSelector: $(serviceMeshControlNodeSelector)

- name: servicemesh-gateway
  override:
    IstioOperator.revision: $(istioRevision)
    IstioOperator.image.hub: docker.io/istio
    IstioOperator.image.tag: $(istioImageTag)
    IstioOperator.values.global.istioNamespace: istio-system
    IstioOperator.components.ingressGateways.name: istio-ingress-gateway
    IstioOperator.components.ingressGateways.namespace: istio-system
    IstioOperator.components.ingressGateways.label: $(ingressGatewayLabel)
    IstioOperator.components.ingressGateways.enabled: true
    IstioOperator.components.ingressGateways.k8s.resources.requests.cpu: 500m
    IstioOperator.components.ingressGateways.k8s.resources.requests.memory: 1024Mi
    IstioOperator.components.ingressGateways.k8s.hpaSpec.minReplicas: 1
    IstioOperator.components.ingressGateways.k8s.nodeSelector: $(serviceMeshIngressNodeSelector)
    IstioOperator.components.ingressGateways.k8s.service.type: NodePort
    IstioOperator.components.ingressGateways.k8s.service.ports.httpNodePort: 31081
    IstioOperator.components.ingressGateways.k8s.service.ports.httpsNodePort: 31443
    IstioOperator.components.egressGateways.name: istio-egress-gateway
    IstioOperator.components.egressGateways.namespace: istio-system
    IstioOperator.components.egressGateways.label: $(egressGatewayLabel)
    IstioOperator.components.egressGateways.enabled: false
    IstioOperator.components.egressGateways.k8s.resources.requests.cpu: 500m
    IstioOperator.components.egressGateways.k8s.resources.requests.memory: 1024Mi
    IstioOperator.components.egressGateways.k8s.hpaSpec.minReplicas: 1
    IstioOperator.components.egressGateways.k8s.nodeSelector: $(serviceMeshEgressNodeSelector)

- name: jaeger-operator
  override:
    nodeSelector: $(serviceMeshControlNodeSelector)

- name: servicemesh-jaeger-resource
  override:
    namespace: istio-system
    logLevel: debug
    collector.resources.requests.cpu: 500m
    collector.resources.requests.memory: 1Gi
    collector.resources.limits.cpu: '1'
    collector.resources.limits.memory: 2Gi
    storage.options.es:
      serverUrls: https://eck-elasticsearch-es-http.lma.svc:9200
      username: elastic
      password: tacoword
    JaegerIngress:
      enabled: true
      namespace: istio-system
      rules:
      - host: jaeger.k2-node01
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-operator-jaeger-query
                port:
                  number: 16686

- name: kiali-operator
  override:
    nodeSelector: $(serviceMeshControlNodeSelector)

- name: servicemesh-kiali-resource
  override:
    istioComponentNamespaces.prometheus: lma
    istioNamespace: istio-system
    deployment.resources.requests.cpu: 500m
    deployment.resources.requests.memory: 1024Mi
    deployment.resources.limits.cpu: 1000m
    deployment.resources.limits.memory: 2048Mi
    deployment.nodeSelector: $(serviceMeshControlNodeSelector)
    externalServices.istio.configMapName: istio-$(istioRevision)
    externalServices.istio.istioIdentityDomain: "svc.cluster.local"
    externalServices.prometheus.url: http://lma-prometheus.lma.svc:9090
    externalServices.tracing.inClusterUrl: http://jaeger-operator-jaeger-query.istio-system:16686
    externalServices.grafana.auth.username: admin
    externalServices.grafana.auth.password: password
    externalServices.grafana.inClusterUrl: http://grafana.lma.svc:80
    externalServices.grafana.url: http://k2-master01:30009
    KialiIngress:
      enabled: true
      namespace: istio-system
      rules:
      - host: kiali.k2-node01
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kaili
                port:
                  number: 20001

- name: servicemesh-grafana-dashboard
  override:
    namespace: istio-system
    datasources.prometheusAddress: fed-master-prometheus.lma.svc:9090

- name: servicemesh-prometheusmonitor
  override:
    namespace: istio-system
    istio.interval: "15s"
    jaeger.interval: "15s"

- name: servicemesh-prometheusrule
  override:
    namespace: istio-system
    aggregation.interval: "15s"
    optimization.interval: "15s"
